### ISSUE TITLE
Use custom CSS instead of maintaining a whole theme

### ISSUE THREAD

**Issue by nodiscc** [xfnw/shaarli-default-dark#1]
From https://github.com/shaarli/Shaarli/pull/1481

>I wouldn't recommend to maintain a whole theme if you only changed colors though.
>I think this can be achieved either using a custom user CSS file or the default_colors plugin.

>The solution :
>https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

@xfnw can you try to achieve the desired result with custom CSS or the default_colors plugin? It would be less work than maintaing a whole theme just for this. Then we can add your custom CSS to https://shaarli.readthedocs.io/en/master/dev/Theming/#themes_1

**Comment by nickbp** [comment]
I am using this theme on Shaarli v0.12.1 (current latest) using the ["Custom CSS"](https://shaarli.readthedocs.io/en/rtfd/Theming/#custom-css) method:

1. Copy the theme customizations from this theme's [`shaarli.min.css` lines 21-259](https://github.com/xfnw/shaarli-default-dark/blob/master/css/shaarli.min.css#L21-L259) (meanwhile lines 1-20 are from the original Shaarli theme and aren't needed)
2. Paste those lines into a new `data/user.css` file in the Shaarli install directory (or `/var/www/shaarli/data/user.css` if using the Shaarli docker image)
3. Restart Shaarli for the custom CSS to take effect

I recommend this method because it just acts as an override to the default colors and avoids making changes to Shaarli's templates, which may vary depending on the version of Shaarli.
